FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir uvicorn

COPY python_microservices /app/python_microservices
COPY src/config.toml /app/src/config.toml

ENV PYTHONPATH=/app

CMD ["uvicorn"]
